mmitem:
  yukiti_ticket:
    itemdisplay: "&3一万円"
    sellprice: 10000
  itiyou_ticket:
    itemdisplay: "&3五千円"
    sellprice: 5000
  syurei_ticket:
    itemdisplay: "&3二千円"
    sellprice: 2000
  noguti_ticket:
    itemdisplay: "&3千円"
    sellprice: 1000
  assyukuwheat:
    itemdisplay: "圧縮小麦チケット"
    sellprice: 1920
  assyukupotato:
    itemdisplay: "圧縮ポテトチケット"
    sellprice: 1920
  assyukucarrot:
    itemdisplay: "圧縮人参チケット"
    sellprice: 1920
  assyukuspruce:
    itemdisplay: "圧縮松の木チケット"
    sellprice: 640
SellItemDisplay: "----------------------------\n[smg 販売リスト]
\n&3一万円&r,&3五千円&r
\n&3二千円&r,&3千円&r
\n&6&l硬貨&r,&7洞窟の欠片&r
\n&0&l黒曜石&r,圧縮小麦チケット
\n圧縮ポテトチケット,圧縮人参チケット
\n----------------------------"